config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'admin/accounts#index'
  get 'admin', to: redirect('/admin/accounts')

  namespace :admin do
    resources :products, :users

    resources :accounts do
      resources :subscriptions
      resources :license_assignments
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  has_many :subscriptions, dependent: :destroy
  has_many :products, through: :subscriptions
  has_many :users, dependent: :destroy
  has_many :license_assignments, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/accounts_controller.rb
# frozen_string_literal: true

module Admin
  class AccountsController < Admin::AdminController
    before_action :set_account, only: %i[show edit update]

    def index
      @accounts = Account.all
    end

    def show; end

    def edit; end

    def update
      @account.update(account_params)
      respond_with(:admin, @account)
    end

    def new
      @account = Account.new
    end

    def create
      @account = Account.new(account_params)
      @account.save
      respond_with(:admin, @account)
    end

    private

    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:name)
    end
  end
end

app/views/admin/accounts/_form.html.erb
<%= form_with model: [:admin, @account], local: true do |form| %>
  <%= render 'components/form_errors', object: @account %>

  <h2>Account</h2>
  
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= link_to 'Cancel', admin_accounts_path %>
    <%= form.submit 'Save' %>
  </div>
<% end %>

app/views/admin/accounts/index.html.erb
<h1>Accounts</h1>
<p>A list of all accounts in your system.</p>
<div>
  <%= link_to 'Create new account', new_admin_account_path %>
</div>
<table>
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">
        <span>Actions</span>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.id %></td>
        <td><%= account.name %></td>
        <td>
          <%= link_to 'Show', admin_account_path(account) %>
          <%= link_to 'Edit', edit_admin_account_path(account) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/accounts/show.html.erb
<div>
  <div>
    <h1>Account: <%= @account.name %></h1>
    <p>Account Details</p>
  </div>
  <div>
    <%= link_to edit_admin_account_path(@account) do %>
      Edit Account
    <% end %>
    <%= link_to admin_accounts_path do %>
      All Accounts
    <% end %>
  </div>

  <hr />

  <div>
    <h2>
      Account Information
    </h2>
    <div>
      <div>
        <p>Account Name</p>
        <p><%= @account.name %></p>
      </div>
      <div>
        <p>Created On</p>
        <p><%= @account.created_at.strftime("%B %d, %Y") %></p>
      </div>
    </div>

    <hr/>

    <div>
      <%= render 'admin/subscriptions/subscriptions', subscriptions: @account.subscriptions %>
    </div>

    <hr />

    <div>
      <%= render 'admin/license_assignments/license_assignments', license_assignments: @account.license_assignments.includes(:user, :product).order(created_at: :desc) %>
    </div>
  </div>
</div>