config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'admin/accounts#index'
  get 'admin', to: redirect('/admin/accounts')

  namespace :admin do
    resources :products, :users

    resources :accounts do
      resources :subscriptions
      resources :license_assignments
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :name, presence: true
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

module Admin
  class ProductsController < Admin::AdminController
    before_action :set_product, only: %i[show edit update]

    def index
      @products = Product.all
    end

    def show; end

    def edit; end

    def update
      @product.update(product_params)
      respond_with(:admin, @product)
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      @product.save
      respond_with(:admin, @product)
    end

    private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description)
    end
  end
end

app/views/admin/products/_form.html.erb
<%= form_with model: [:admin, @product], local: true do |form| %>
  <%= render 'components/form_errors', object: @product %>

  <h2>Product</h2>
  
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4 %>
  </div>

  <div>
    <%= link_to 'Cancel', admin_products_path %>
    <%= form.submit 'Save' %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<%= render 'form' %>

app/views/admin/products/index.html.erb
<h1>Products</h1>
<p>A list of all products in your system including their name and description.</p>

<%= link_to 'Create new product', new_admin_product_path %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td>
          <%= link_to 'Show', admin_product_path(product) %>
          <%= link_to 'Edit', edit_admin_product_path(product) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/show.html.erb
<%= @product.inspect %>