config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'admin/accounts#index'
  get 'admin', to: redirect('/admin/accounts')

  namespace :admin do
    resources :products, :users

    resources :accounts do
      resources :subscriptions
      resources :license_assignments
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  belongs_to :account

  validates :email, presence: true, uniqueness: true
  validates :account_id, presence: true
  validates :name, presence: true
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < Admin::AdminController
    before_action :set_user, only: %i[show edit update]

    def index
      @users = User.all
    end

    def show; end

    def edit; end

    def update
      @user.update(user_params)
      respond_with(:admin, @user)
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      @user.save
      respond_with(:admin, @user)
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :account_id)
    end
  end
end

app/views/admin/users/_form.html.erb
<%= form_with model: [:admin, @user], local: true do |form| %>
  <%= render 'components/form_errors', object: @user %>

  <div>
    <div>
      <h2>User</h2>
      <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>

      <div>
        <%= form.label :email %>
        <%= form.email_field :email %>
      </div>

      <div>
        <%= form.label :account %>
        <%= form.collection_select :account_id, Account.all, :id, :name, 
          { prompt: 'Select one account' }, 
          { 
            id: 'account_id'
          } %>
      </div>
    </div>
  </div>

  <div>
    <%= link_to 'Cancel', admin_users_path %>
    <%= form.submit 'Save' %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<h1>Users</h1>
<p>A list of all users in your system including their name and e-mail.</p>
<div>
  <%= link_to 'Create new user', new_admin_user_path %>
</div>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Account</th>
      <th>
        <span>Actions</span>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.account.name %></td>
        <td>
          <%= link_to 'Show', admin_user_path(user) %>
          <%= link_to 'Edit', edit_admin_user_path(user) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<%= render 'form' %>

app/views/admin/users/show.html.erb
<%= @user.inspect %>