config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'admin/accounts#index'
  get 'admin', to: redirect('/admin/accounts')

  namespace :admin do
    resources :products, :users

    resources :accounts do
      resources :subscriptions
      resources :license_assignments
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  belongs_to :account
  belongs_to :product

  validates :account_id, :product_id, :issued_at, :expires_at, presence: true
  validates :number_of_licenses, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def available_licenses
    number_of_licenses - account.license_assignments.where(product: product).count
  end
end

app/controllers/admin/subscriptions_controller.rb
# frozen_string_literal: true

module Admin
  class SubscriptionsController < Admin::AdminController
    before_action :set_subscription, only: %i[edit update destroy]
    before_action :set_account
    before_action :set_products, only: %i[new create edit update]

    def edit; end

    def update
      @subscription.update(subscription_params)
      respond_with(:admin, @account, @subscription, location: admin_account_path(@account))
    end

    def new
      @subscription = Subscription.new
    end

    def create
      @subscription = Subscription.new(subscription_params)
      @subscription.account_id = @account.id
      @subscription.save
      respond_with(:admin, @account, @subscription, location: admin_account_path(@account))
    end

    def destroy
      @subscription.destroy
      respond_with(:admin, @account, location: admin_account_path(@account))
    end

    private

    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    def set_account
      @account = Account.find(params[:account_id])
    end

    def set_products
      @products = Product.all
    end

    def subscription_params
      params.require(:subscription).permit(:product_id, :number_of_licenses,
                                           :issued_at, :expires_at)
    end
  end
end

app/views/admin/subscriptions/_form.html.erb
<div>
  <div>
    <h3>
      <%= @subscription.persisted? ? "Edit Subscription" : "Create New Subscription" %>
    </h3>
    <p>Configure subscription details for <b><%= @account.name %></b></p>
  </div>

  <%= form_with model: [:admin, @account, @subscription], local: true do |form| %>
    <%= render 'components/form_errors', object: @subscription %>

    <div>
      <%= form.label :product_id %>
      <%= form.select :product_id, 
          options_from_collection_for_select(@products, :id, :name, @subscription.product_id),
          { prompt: "Select a product" } %>
    </div>

    <div>
      <%= form.label :number_of_licenses %>
      <%= form.number_field :number_of_licenses, 
          min: 1, 
          placeholder: "Enter number of licenses",
          value: @subscription.number_of_licenses %>
    </div>

    <div>
      <div>
        <%= form.label :issued_at %>
        <%= form.datetime_local_field :issued_at, 
            value: @subscription.issued_at&.strftime("%Y-%m-%dT%H:%M") || Time.current.strftime("%Y-%m-%dT%H:%M") %>
      </div>

      <div>
        <%= form.label :expires_at %>
        <%= form.datetime_local_field :expires_at, 
            value: @subscription.expires_at&.strftime("%Y-%m-%dT%H:%M") %>
      </div>
    </div>

    <div style="margin-top: 10px; display: flex; gap: 10px;">
      <%= link_to "Cancel", :back %>
      
      <%= form.submit (@subscription.persisted? ? "Update Subscription" : "Create Subscription") %>
    </div>
  <% end %>
</div>

app/views/admin/subscriptions/_subscriptions.html.erb
<div>
  <h2>Subscriptions</h2>

  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Product</th>
        <th>Licenses</th>
        <th>Issued At</th>
        <th>Expires At</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% subscriptions.each do |subscription| %>
        <tr>
          <td><%= subscription.id %></td>
          <td><%= subscription.product.name %></td>
          <td><%= subscription.number_of_licenses %></td>
          <td><%= subscription.issued_at.strftime("%d/%m/%Y %H:%M") if subscription.issued_at %></td>
          <td><%= subscription.expires_at.strftime("%d/%m/%Y %H:%M") if subscription.expires_at %></td>
          <td>
            <% if subscription.expires_at && subscription.expires_at < Time.current %>
              Expired
            <% elsif subscription.issued_at && subscription.issued_at > Time.current %>
              Pending
            <% else %>
              Active
            <% end %>
          </td>
          <td>
            <%= link_to "Edit", edit_admin_account_subscription_path(@account, subscription) %>
            <%= link_to "Delete", admin_account_subscription_path(@account, subscription),
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this subscription?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div>
    <%= link_to 'Create new subscription', new_admin_account_subscription_path(@account) %>
  </div>
</div>

app/views/admin/subscriptions/edit.html.erb
<%= render 'form' %>

app/views/admin/subscriptions/index.html.erb
<%= render 'subscriptions', subscriptions: @subscriptions %>

app/views/admin/subscriptions/new.html.erb
<%= render 'form' %>